### ISSUE TITLE
CommandLineF4 редактировать при погашенных панелях

### ISSUE THREAD

**Issue by wave-blessed** [z0hm/far-scripts#1]
Предлагаю добавить `condition = function() return not APanel.Visible end;` в макрос редактирования командной строки. В конце концов, гораздо чаще приходится редактировать файлы, чем комстроку.  И поэтому, если в строке что-то есть и надо отредактировать файл, то приходится сначала очищать её, потом редактировать, потом, при необходимости, возвращать, что там было. А так — всё просто: надо редактировать файл — редактируешь файл, надо редактировать комстроку — гасишь панели и редактируешь комстроку.

**Comment by z0hm** [comment]
Не соглашусь - раз в комстроке что-то есть, значит начал набирать и понял, что удобнее будет продолжить в редакторе. Панели гашу ESC, он же очищает строку, если в ней что-то есть - т.е. методы работы у нас отличны и ваш вариант не подходит.

**Comment by wave-blessed** [comment]
Я тоже по ESC гашу панели и очищаю комстроку, а также печатаю и navigating (брожу по папкам и всё прочее) в ФАРе вслепую. Просто случается, что в комстроку попадает и остаётся незамеченной зацепленная буква или какой-нибудь знак. Для клавиш навигации это не проблема. Для перехода по каталогам случается запинка, мол, команда ъ не может быть выполнена. А вот редактирование уже неприятно в таких случаях запинается — открывает на редактирование не то, что я хотел. Я именно после пары подобных запинок и открыл это issue.

С другой стороны, если что-то набрал, но всё равно хочешь открыть на редактирование файл, то начинаются танцы: вырезать комстроку в буфер обмена, сделать, что нужно, не затерев при этом буфер, или же из буфера временно в редактор вставить… А при реализации моего предложения легко редактируется отдельно файл, отдельно комстрока.

Впрочем, я свою идею высказал, если она не подошла, issue можно закрывать. Хотя можно заморочиться и добавить логики на CtrlO, например, что если не пустая комстрока, то открывать её на редактирование, или ещё какую-нибудь логику придумать. Но я себе, если надо, такую мелочь могу поправить, а вы — по желанию.

**Comment by z0hm** [comment]
По FS бодится с помощью 2-х кнопок курсора - left/right, редко лифты по enter, поэтому в комстроку у меня попадает всё целенаправленно, но если случайно что-то левое попало, то ESC очищает.
